# Generated by Django 5.1.5 on 2025-02-17 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nogoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nogs', to='nogoff.event'),
        ),
    ]
