# Generated by Django 5.1.5 on 2025-10-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nogoff', '0002_alter_nog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nogoff.event'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nogoff.nog'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nogoff.user'),
        ),
    ]
