# Generated by Django 5.1.5 on 2025-10-22 13:16

from django.db import migrations, models


def auto_increment_nog_numbers(apps, schema_editor):
    """
    Assign sequential numbers to Nogs for each Event
    """
    Event = apps.get_model("nogoff", "Event")
    Nog = apps.get_model("nogoff", "Nog")

    for event in Event.objects.all():
        for i, nog in enumerate(
            Nog.objects.filter(event=event).order_by("id"), start=1
        ):
            nog.number = i
            nog.save()


def reverse_migration(apps, schema_editor):
    """
    Reset Nogs to default
    """
    Nog = apps.get_model("nogoff", "Nog")
    Nog.objects.all(number=99)


class Migration(migrations.Migration):
    dependencies = [
        ("nogoff", "0003_alter_vote_event_alter_vote_nog_alter_vote_user"),
    ]
    operations = [
        migrations.AddField(
            model_name="nog",
            name="number",
            field=models.IntegerField(default=99),
        ),
        migrations.RunPython(
            auto_increment_nog_numbers,
            reverse_migration,
        ),
        migrations.AlterUniqueTogether(
            name="nog",
            unique_together={("event", "number")},
        ),
    ]
