# Generated by Django 5.2.9 on 2026-04-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nogoff', '0005_auto_increment_nog_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_json', models.JSONField(help_text='The subscription object from the Push API')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nog',
            name='creator',
            field=models.CharField(max_length=200, verbose_name='Creator'),
        ),
        migrations.AddConstraint(
            model_name='nog',
            constraint=models.UniqueConstraint(fields=('event', 'number'), name='unique_nog_per_event'),
        ),
        migrations.AddField(
            model_name='pushnotificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='nogoff.user'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='nogoff.user'),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('user', 'subscription_json')},
        ),
    ]
