# Generated by Django 5.2.9 on 2026-08-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nogoff', '0006_pushnotificationlog_pushsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically once the voting-closes-soon reminder has been sent for this event. Clear it to allow the reminder to be sent again.', null=True, verbose_name='Voting Reminder Sent At'),
        ),
        migrations.AddField(
            model_name='settings',
            name='voting_reminder_minutes_before_end',
            field=models.PositiveIntegerField(default=30, help_text="How many minutes before an event's voting closes to send a push notification reminder.", verbose_name='Voting Reminder (minutes before voting ends)'),
        ),
    ]
